let money = 100000;
console.log('money: ', money);
console.log(typeof money);
const income = '2000р.'; 
console.log('income: ', income);
console.log(typeof  income);
console.log(income.length);
let addExpenses = ('1000Р., 2000р., 4000Р.');
console.log('addExpenses: ', addExpenses);
console.log(typeof  addExpenses);
console.log(addExpenses.toLowerCase());
console.log(addExpenses.split(', '));
const deposit = true;
console.log('deposit: ', deposit);
console.log(typeof  deposit);
let mission = 500000;
console.log('mission: ', mission);
console.log(typeof  mission);
console.log('“Цель заработать ' + (mission) + ' рублей”');
let period = 5;
console.log('period: ', period);
console.log(typeof  period);
console.log('“Период ' + (period) + ' месяцев”');  
let budgetDay = 0;
budgetDay = money / 30;
console.log('budgetDay: ', budgetDay);
budgetDay = money % 30;
console.log('budgetDay: ', budgetDay);

alert("ввод данных окончен!");

